#!/bin/bash
BASEDIR=$(dirname "$0")
filename="${1%.*}"
if [ -z $2 ]; then
  pandoc -f markdown -t html --template=${BASEDIR}/article.template --mathjax --number-sections --number-offset=0 --toc ${1} -o ${filename}.html
else
  pandoc -f markdown -t html --template=${BASEDIR}/article.template --mathjax --number-sections --number-offset=0 --toc ${1} -o ${2}
fi
# pandoc -f markdown -t html --filter pandoc-fignos --filter ${BASEDIR}/sidenote.py --template=${BASEDIR}/article.template --mathjax --number-sections --number-offset=0 --toc ${1} -o ${filename}.html
# pandoc -f markdown -t html --filter ${BASEDIR}/sidenote.py --template=${BASEDIR}/article.template --mathjax --number-sections --number-offset=0 --toc ${1} -o ${filename}.html
# Modify table in html
table_line_nos=$(sed -n '/\<table style/=' ${filename}.html)
for i_table_line in $table_line_nos; do
  sed -i ${i_table_line}'a\<table\>' ${filename}.html
  sed -i ${i_table_line}'d' ${filename}.html
done
