#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# invoke global X session script
# . /etc/X11/Xsession

# exec /home/jcshi/Softwares/i3/usr/bin/i3 -V >> ~/i3log-$(date +'%F-%k-%M-%S') 2>&1
exec i3 -V >> $HOME/i3log-$(date +'%F-%k-%M-%S') 2>&1
